### ISSUE TITLE
Error: Cannot find module '../build/default/poppler'

### ISSUE THREAD

**Issue by msageryd** [blackbeam/poppler-simple#32]
I just installed poppler and poppler-simple on a new OSX machine (Catalina).

When I try to use poppler-simple I get:
`Error: Cannot find module '../build/default/poppler'`

There is no such folder. But there is a `../build/Release/poppler`

Did I miss something in the installation?
The first installation attempt failed due to missing pkg-config. 
This was solved with `brew install pkg-config`.

I tried to `rm -rf node_modules` and start over, but the problem did not go away. 

The poppler-simple install seems to go well, but there is one warning:
`ld: warning: dylib (/usr/local/Cellar/poppler/20.09.0/lib/libpoppler.dylib) was built for newer macOS version (10.15) than being linked (10.10)`

**Comment by blackbeam** [comment]
Hi. Thanks for report.
Which nodejs and npm versions do you use?

**Comment by msageryd** [comment]
I'm using NVM.
Tried with Node 10.16.2 and 12.18.4

The last time I used popper-simple was a couple of years ago. I used Node 8 at that time (remember this because I wrote it in the docker.example file).
On 22 Sep 2020, 21:00 +0200, Anatoly I <notifications@github.com>, wrote:

Hi. Thanks for report.
Which nodejs and npm versions do you use?

**Comment by blackbeam** [comment]
Should work in [v0.9.0](https://github.com/blackbeam/poppler-simple/releases/tag/v0.9.0).

**Comment by msageryd** [comment]
Thank you.
Unfortunately it still doesn't work for me. I removed poppler-simple and npm installed it again.

poppler-simple looks like this in my node_modules folder. Still no *default* folder under build:
![image](https://user-images.githubusercontent.com/4483085/94184238-e72f9100-fea3-11ea-9592-9e7df1915744.png)

I package.json in this module says 0.9.0, so the install seems to have worked.

**Comment by blackbeam** [comment]
Ok. Then can you please try to load `poppler.node` manually? Something like this from poppler-simple directory:

```javascript
require('./build/Release/poppler');
```

**Comment by blackbeam** [comment]
> Still no default folder under build:

The _default_ folder is just the last one of many folders, that the library will probe during startup. That's why it is in the error message (I'll improve error reporting). The actual error is hidden and, I believe, is emitted here:

https://github.com/blackbeam/poppler-simple/blob/a7f9702b7ccc7bdc1395432d164a45ecc33140b1/lib/poppler.js#L7-L9

That's why I asked you to perform this `require` manually.

In my case the error was `Unknown symbol ...` and I've fixed it in 23c1c9e.

**Comment by blackbeam** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by rigwild** [comment]
I have the same issue.

```
(node:29531) UnhandledPromiseRejectionWarning: Error: Cannot find module '../build/default/poppler'
Require stack:
- /home/rigwild/dev/bulk-images-ocr-search/node_modules/poppler-simple/lib/poppler.js
- /home/rigwild/dev/bulk-images-ocr-search/node_modules/calipers-pdf/lib/index.js
- /home/rigwild/dev/bulk-images-ocr-search/node_modules/calipers/lib/index.js
- /home/rigwild/dev/bulk-images-ocr-search/dist/utils.js
- /home/rigwild/dev/bulk-images-ocr-search/dist/worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /home/rigwild/dev/bulk-images-ocr-search/node_modules/poppler-simple/lib/poppler.js:11:26
    at Object.<anonymous> (/home/rigwild/dev/bulk-images-ocr-search/node_modules/poppler-simple/lib/poppler.js:100:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/rigwild/dev/bulk-images-ocr-search/node_modules/calipers-pdf/lib/index.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

Here is the output of:
> ```js
> require('./build/Release/poppler');
> ```

```
$ node node_modules/poppler-simple/aaa.js
{
  "POPPLER_VERSION_MAJOR": 0,
  "POPPLER_VERSION_MINOR": 71,
  "POPPLER_VERSION_MICRO": 0
}
```

I am using Node.js v14.18.2 (tried on v16, same) and yarn v1.22.15.
